<script lang="ts" setup>
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: need to figure out to get typing with emscripten output
import LAG_WASM from "../../../lag_wasm/lag.mjs";
import ProjectPageLayout from "@/components/layout/ProjectPageLayout.vue";
import { ref } from "vue";
import EmscriptenLogo from "@/assets/ext-logos/emscripten-logo.png";
import WASMLogo from "@/assets/ext-logos/wasm-logo.png";
import CppLogo from "@/assets/ext-logos/cpp-logo.png";
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";
import { faFileArrowDown, faPlay } from "@fortawesome/free-solid-svg-icons";
import { faGitAlt } from "@fortawesome/free-brands-svg-icons";

const inputText = ref(
  `
class alpha [a-zA-Z_]
class digit [0-9]
class whitespace [\\n\\t\\f\\v\\r\\ ]

token Ident /[alpha]([alpha]|[digit])* /

ignore /[whitespace]+/
`.trim(),
);

const headerFile = ref<string | null>(null);
const bodyFile = ref<string | null>(null);
const outputText = ref("");

const terminalFont = '"Lucida Console", Monaco, monospace';

async function runLAG() {
  const module = await LAG_WASM({
    print: (function () {
      const element = document.getElementById("lag-output");
      if (!element) {
        throw new Error("Couldn't find the lag-output element!");
      }
      return function (text: string) {
        outputText.value += text + "\n";
        element.scrollTop = element.scrollHeight;
      };
    })(),
  });

  // Write user input to input.txt virtual file
  // let data = stringToBytes(this.inputText);
  module.FS.writeFile("input.txt", inputText.value);
  module.FS.writeFile("LexicalAnalyzer.h", "");
  module.FS.writeFile("LexicalAnalyzer.cpp", "");

  // Call C++ function
  module.ccall(
    "run",
    null,
    ["string", "string", "string"],
    ["input.txt", "LexicalAnalyzer", ""],
  );

  // Read in generated virtual files
  let headerFileText = module.FS.readFile("LexicalAnalyzer.h", {
    encoding: "utf8",
    flags: "r",
  });
  let bodyFileText = module.FS.readFile("LexicalAnalyzer.cpp", {
    encoding: "utf8",
    flags: "r",
  });

  // Write text to a blob for file download
  let headerFileBlobData = new Blob([headerFileText], {
    type: "text/plain",
  });
  let bodyFileBlobData = new Blob([bodyFileText], { type: "text/plain" });

  // If replacing a previously generated file,
  // manually revoke the object URL to avoid memory leaks.
  if (typeof headerFile.value === "string") {
    window.URL.revokeObjectURL(headerFile.value);
  }
  if (typeof bodyFile.value === "string") {
    window.URL.revokeObjectURL(bodyFile.value);
  }

  // Expose the generated files as a downloadable link
  headerFile.value = window.URL.createObjectURL(headerFileBlobData);
  bodyFile.value = window.URL.createObjectURL(bodyFileBlobData);
}

const technologies = [
  {
    name: "C++",
    description: "Source code",
    imgSrc: CppLogo,
  },
  {
    name: "Web Assembly",
    description: "How you're running the program here 😉",
    imgSrc: WASMLogo,
  },
  {
    name: "Emscripten",
    description: "Compile c/c++ to WASM and JS",
    imgSrc: EmscriptenLogo,
  },
];

const links = [
  {
    href: "https://github.com/kmdiogo/LAG/tree/wasm",
    icon: faGitAlt,
  },
];
</script>

<template>
  <ProjectPageLayout
    title="Lexical Analyzer Generator"
    description=""
    :technologies="technologies"
    :links="links"
  >
    <div class="text-page d-flex flex-column">
      <h4>
        Welcome to my Lexical Analyzer Generator! The original program is
        written in C++. This is a slightly modified version that is compiled
        using
        <a href="https://emscripten.org/index.html">Emscripten</a> and is ran in
        your browser with <a href="https://webassembly.org/">WebAssembly!</a>
      </h4>

      <h3 class="m-0 font-bold text-lg">What it does</h3>
      <p class="mt-0">
        Given a list of tokens, this program will generate a C++ Lexical
        Analyzer class. The DFA that drives the Lexical Analyzer is generated by
        first creating an NFA using
        <a href="https://en.wikipedia.org/wiki/Thompson%27s_construction"
          >Thompson's Construction Algorithm</a
        >
        then converting that NFA to a DFA using
        <a href="https://en.wikipedia.org/wiki/Powerset_construction"
          >Powerset Construction</a
        >
      </p>

      <h3 class="m-0 font-bold text-lg">Instructions</h3>
      <div class="instructions">
        <p class="m-0">
          Use the input box below to define the tokens you want the Analyzer to
          recognize. The tokens are defined using regular expressions. Character
          sets are supported. You can also define ignore sequences which the
          Analyzer will recognize but not return anything. A template is already
          provided to show how to define standard C++ identifier tokens.
        </p>

        <p>
          Once your tokens are defined, click the run button. Two download links
          will appear below the input box. One is a header file and the other is
          a cpp file for the Lexical Analyzer class.
        </p>
      </div>
    </div>
    <template v-slot:extra-content>
      <div class="flex flex-col mt-2">
        <h3 class="font-bold text-lg">Input:</h3>
        <div>
          <textarea
            class="w-full text-black bg-gray-50 p-1 text-sm leading-tight"
            v-model="inputText"
            rows="12"
          ></textarea>
        </div>
        <button
          class="p-3 w-full bg-forest-green-500 rounded hover:text-white hover:bg-forest-green-600 transition-colors duration-100"
          @click="runLAG"
        >
          <FontAwesomeIcon :icon="faPlay" size="lg" />
        </button>

        <h3 class="font-bold text-lg mt-6">Output:</h3>
        <div class="grid grid-cols-12">
          <textarea
            class="w-full bg-black text-white outline-none border border-darcula-300 lg:col-span-8 col-span-12"
            disabled
            rows="12"
            :style="{ 'font-family': terminalFont }"
            v-model="outputText"
            id="lag-output"
          ></textarea>

          <div
            class="lg:col-span-4 col-span-12 border border-darcula-300 p-4 flex flex-col"
          >
            <span>File output</span>
            <hr class="mt-1 mb-3" />
            <div class="flex flex-col gap-2">
              <a
                class="hover:text-white"
                :href="headerFile"
                download="LexicalAnalyzer.h"
                v-if="headerFile"
              >
                <FontAwesomeIcon :icon="faFileArrowDown" />
                LexicalAnalyzer.h
              </a>
              <a
                class="hover:text-white"
                :href="bodyFile"
                download="LexicalAnalyzer.cpp"
                v-if="bodyFile"
              >
                <FontAwesomeIcon :icon="faFileArrowDown" />
                LexicalAnaylzer.cpp
              </a>
            </div>
          </div>
        </div>
      </div>
    </template>
  </ProjectPageLayout>
</template>
