name: CI/CD

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node v16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm

      - name: Install npm Dependencies
        run: npm ci
        shell: bash

      - name: Prettier
        run: npm run format-check

      - name: Eslint
        run: npm run eslint

      - name: Hadolint
        run: npm run hadolint

      - name: Verify Build LAG WASM
        run: npm run build-lag

  cd:
    needs:
      - ci
    if: success() && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node v16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm

      - name: Install npm Dependencies
        run: npm ci
        shell: bash

      - name: Build LAG WASM
        run: npm run build-lag

      - name: Build Vue.js App
        run: npm run build

      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          external_repository: kmdiogo/kmdiogo.github.io
          publish_branch: master
          publish_dir: ./dist
