name: Deploy Application

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node v16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install npm Dependencies
        run: npm ci
      - name: Prettier
        run: npm run format-check
      - name: Eslint
        run: npm run eslint
      - name: Build LAG WASM
        run: npm run build-lag
      - name: Build Vue.js App
        run: npm run build
      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: kmdiogo/kmdiogo.github.io
          publish_branch: master
          publish_dir: ./dist
